export const cardConfig = {
  bang: {
    id: "bang",
    title: "Bang",
    eventTitle: "БЭНГ",
    image: "/images/cards/bang.webp",
    playMode: "instant",
    eventColor: "#c94a35",
    action: "bang",
    reactionTo: ["indians", "duel"],
    selectionView: "players",
    needsTarget: true,
    usesWeaponRange: true,
    disposable: true,
    effectLimitKey: "bang",
  },
  gatling: {
    id: "gatling",
    title: "Gatling",
    eventTitle: "Гатлинг",
    image: "/images/cards/gatling.webp",
    playMode: "instant",
    eventColor: "#c94a35",
    action: "gatling",
    needsTarget: false,
    disposable: true,
  },
  indians: {
    id: "indians",
    title: "Indians",
    eventTitle: "Индейцы",
    image: "/images/cards/indians.webp",
    playMode: "instant",
    eventColor: "#c94a35",
    action: "indians",
    needsTarget: false,
    disposable: true,
  },
  duel: {
    id: "duel",
    title: "Дуэль",
    eventTitle: "Дуэль",
    image: "/images/cards/duel.webp",
    playMode: "instant",
    eventColor: "#c94a35",
    action: "duel",
    selectionView: "players",
    needsTarget: true,
    disposable: true,
  },
  panic: {
    id: "panic",
    title: "Паника",
    eventTitle: "Паника",
    image: "/images/cards/panic.webp",
    playMode: "instant",
    eventColor: "#000",
    action: "panic",
    selectionView: "players",
    needsTarget: true,
    panicDistance: 1,
    targetTableCardMode: "take",
    disposable: true,
  },
  catbalou: {
    id: "catbalou",
    title: "Красотка",
    eventTitle: "Красотка",
    image: "/images/cards/catbalou.webp",
    playMode: "instant",
    eventColor: "#000",
    action: "catbalou",
    selectionView: "players",
    needsTarget: true,
    targetTableCardMode: "discard",
    disposable: true,
  },
  missed: {
    id: "missed",
    title: "Missed",
    eventTitle: "МИМО",
    image: "/images/cards/missed.webp",
    playMode: "reaction",
    eventColor: "#42AAFF",
    action: "missed",
    reactionTo: ["bang", "gatling"],
    needsTarget: false,
    disposable: true,
  },
  beer: {
    id: "beer",
    title: "Beer",
    eventTitle: "ПИВО",
    image: "/images/cards/beer.webp",
    playMode: "instant",
    eventColor: "#FFBF00",
    action: "beer",
    reactionTo: ["bang", "gatling", "indians", "dynamite", "duel"],
    reactionOnLethalHealthLoss: true,
    needsTarget: false,
    disposable: true,
    healAmount: 1,
  },
  saloon: {
    id: "saloon",
    title: "Saloon",
    eventTitle: "Салун",
    image: "/images/cards/saloon.webp",
    playMode: "instant",
    eventColor: "#FFBF00",
    action: "saloon",
    needsTarget: false,
    disposable: true,
    healAmount: 1,
  },
  stagecoach: {
    id: "stagecoach",
    title: "Stagecoach",
    eventTitle: "Дилижанс",
    image: "/images/cards/stagecoach.webp",
    playMode: "instant",
    eventColor: "#50c878",
    action: "drawCards",
    needsTarget: false,
    disposable: true,
    drawCount: 2,
  },
  wellsfargo: {
    id: "wellsfargo",
    title: "Wells Fargo",
    eventTitle: "Уэллс Фарго",
    image: "/images/cards/wellsfargo.webp",
    playMode: "instant",
    eventColor: "#50c878",
    action: "drawCards",
    needsTarget: false,
    disposable: true,
    drawCount: 3,
  },
  generalstore: {
    id: "generalstore",
    title: "Магазин",
    eventTitle: "Магазин",
    image: "/images/cards/generalstore.webp",
    playMode: "instant",
    eventColor: "#50c878",
    action: "generalstore",
    needsTarget: false,
    disposable: true,
  },
  remington: {
    id: "remington",
    title: "Remington",
    eventTitle: "Ремингтон",
    image: "/images/cards/remington.webp",
    playMode: "permanent",
    eventColor: "#975f2a",
    action: "equipWeapon",
    needsTarget: false,
    disposable: false,
    weaponRange: 3,
  },
  carbine: {
    id: "carbine",
    title: "Carbine",
    eventTitle: "Карабин",
    image: "/images/cards/carbine.webp",
    playMode: "permanent",
    eventColor: "#975f2a",
    action: "equipWeapon",
    needsTarget: false,
    disposable: false,
    weaponRange: 4,
  },
  winchester: {
    id: "winchester",
    title: "Winchester",
    eventTitle: "Винчестер",
    image: "/images/cards/winchester.webp",
    playMode: "permanent",
    eventColor: "#975f2a",
    action: "equipWeapon",
    needsTarget: false,
    disposable: false,
    weaponRange: 5,
  },
  scofield: {
    id: "scofield",
    title: "Scofield",
    eventTitle: "Скофилд",
    image: "/images/cards/scofield.webp",
    playMode: "permanent",
    eventColor: "#975f2a",
    action: "equipWeapon",
    needsTarget: false,
    disposable: false,
    weaponRange: 2,
  },
  volcanic: {
    id: "volcanic",
    title: "Volcanic",
    eventTitle: "Волканик",
    image: "/images/cards/volcanic.webp",
    playMode: "permanent",
    eventColor: "#975f2a",
    action: "equipWeapon",
    propertyAction: "unlockEffectLimit",
    propertyEffectLimitKey: "bang",
    propertyCharges: 1,
    propertyLabel: "Можно сыграть еще один БЭНГ",
    needsTarget: false,
    disposable: false,
    weaponRange: 1,
  },
  scope: {
    id: "scope",
    title: "Scope",
    eventTitle: "Прицел",
    image: "/images/cards/scope.webp",
    playMode: "permanent",
    eventColor: "#123c75",
    action: "playBlueCard",
    needsTarget: false,
    disposable: false,
    statusImage: "/images/statuses/scope.webp",
    distanceModifierFromSelf: -1,
    rangeStatusBonus: 1,
  },
  mustang: {
    id: "mustang",
    title: "Mustang",
    eventTitle: "Мустанг",
    image: "/images/cards/mustang.webp",
    playMode: "permanent",
    eventColor: "#123c75",
    action: "playBlueCard",
    needsTarget: false,
    disposable: false,
    statusImage: "/images/statuses/mustang.webp",
    distanceModifierToSelf: 1,
  },
  barrel: {
    id: "barrel",
    title: "Barrel",
    eventTitle: "Бочка",
    image: "/images/cards/barrel.webp",
    playMode: "permanent",
    eventColor: "#123c75",
    action: "playBlueCard",
    needsTarget: false,
    disposable: false,
    statusImage: "/images/statuses/barrel.webp",
    check: {
      timing: "reaction",
      type: "barrel",
    },
  },
  jail: {
    id: "jail",
    title: "Jail",
    eventTitle: "Тюрьма",
    image: "/images/cards/jail.webp",
    playMode: "permanent",
    eventColor: "#123c75",
    action: "playBlueCardOnTarget",
    selectionView: "players",
    needsTarget: true,
    disposable: false,
    statusImage: "/images/statuses/jail.webp",
    check: {
      timing: "turn",
      type: "jail",
    },
  },
  dynamite: {
    id: "dynamite",
    title: "Dynamite",
    eventTitle: "Динамит",
    image: "/images/cards/dynamite.webp",
    playMode: "permanent",
    eventColor: "#c94a35",
    action: "playBlueCardOnTarget",
    selectionView: "players",
    needsTarget: true,
    disposable: false,
    statusImage: "/images/statuses/dynamite.webp",
    check: {
      timing: "turn",
      type: "dynamite",
    },
  },
};
